# **TITLE: PyTorch and Tensor Fundamental**


## **OBJECTIVE**
To understand the basic concepts of PyTorch, tensor creation, tensor operations, data types, shapes, and device management.



## **THEORY**

### Introduction to PyTorch
PyTorch is an open-source deep learning framework developed by Meta AI. It provides a flexible and efficient environment for numerical computation and machine learning. Unlike traditional numerical libraries, PyTorch supports automatic differentiation, making it suitable for training neural networks.

### Why Use PyTorch?
- Dynamic computation graphs
- GPU acceleration support
- Easy debugging and experimentation
- Extensive ecosystem for deep learning and research

### Tensors in PyTorch
A tensor is a multi-dimensional array used to store and manipulate data. Tensors are similar to NumPy arrays but can run on GPUs for faster computation.

### Tensor Dimensions
- **Scalar (0-D Tensor):** A single number, such as 5 or -3.14.
- **Vector (1-D Tensor):** A one-dimensional array, such as [1, 2, 3, 4].
- **Matrix (2-D Tensor):** A two-dimensional array, like a table with rows and columns: [[1, 2], [3, 4]].
- **Tensor (N-D Tensor):** The generalized algebraic framework for multi-dimensional numerical arrays of an arbitrary number of axes (N>3). Tensors handle complex, high-dimensional structures natively, such as color images.

### Common Tensor Operations
PyTorch supports arithmetic operations, reshaping, indexing, aggregation functions, and matrix multiplication. 

These operations form the foundation of machine learning computations.


In [ ]:
import torch
print("PyTorch Version:", torch.__version__)

#### Creating Different Types of Tensors

In [ ]:
scalar = torch.tensor(10)
vector = torch.tensor([1, 2, 3])
matrix = torch.tensor([[1, 2], [3, 4]])

print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:\n", matrix)

### Tensor Attributes

In [ ]:
tensor = torch.rand(3, 4)

print("Shape:", tensor.shape)
print("Datatype:", tensor.dtype)
print("Device:", tensor.device)

#### Random Tensors

In [ ]:
# randomize tensors
# Create a random tensor of size (2, 3)
random_tensor = torch.rand(size=(2, 3))
random_tensor, random_tensor.dtype

(tensor([[0.1978, 0.3092, 0.6292],
         [0.7193, 0.1592, 0.7987]]),
 torch.float32)

In [ ]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#### Tensors of only Zeros and Ones 

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)